basePath: /api
definitions:
  requests.UserRegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  responses.UserRegisterResponse:
    properties:
      username:
        type: string
    type: object
  responses.UserResponse:
    properties:
      user:
        properties:
          id:
            type: integer
          username:
            type: string
        type: object
    type: object
host: eyeh:8080
info:
  contact: {}
  description: Conduit API
  title: Conduit API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: register
      parameters:
      - description: User info for registration
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.UserRegisterResponse'
      summary: Register a new user
      tags:
      - user
  /user:
    get:
      consumes:
      - application/json
      description: Gets the currently logged-in user
      operationId: current-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      summary: Get the current user
      tags:
      - user
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
